// Built-in starter catalogue: well-known released work across all four media.
// Row format: [title, year, creators, genres, moods, description?]

export const MOVIES = [
  ['Heat', 1995, ['Michael Mann'], ['crime', 'action', 'drama'], ['tense', 'gritty', 'epic'], 'A master thief and an obsessive LA detective circle each other.'],
  ['The Godfather', 1972, ['Francis Ford Coppola'], ['crime', 'drama'], ['epic', 'dark', 'gritty'], 'The ageing patriarch of a crime dynasty hands control to his reluctant son.'],
  ['Mad Max: Fury Road', 2015, ['George Miller'], ['action', 'sci-fi'], ['high-energy', 'epic', 'weird'], 'A desert chase across a post-apocalyptic wasteland.'],
  ['Die Hard', 1988, ['John McTiernan'], ['action', 'thriller'], ['high-energy', 'tense', 'funny'], 'A New York cop takes on terrorists in an LA skyscraper.'],
  ['The Thing', 1982, ['John Carpenter'], ['horror', 'sci-fi'], ['dark', 'tense', 'atmospheric'], 'An Antarctic research team meets a shape-shifting alien.'],
  ['Hereditary', 2018, ['Ari Aster'], ['horror', 'drama'], ['dark', 'tense', 'emotional'], 'A grieving family unravels after their secretive grandmother dies.'],
  ['The Shining', 1980, ['Stanley Kubrick'], ['horror'], ['dark', 'atmospheric', 'tense'], 'A writer becomes winter caretaker of an isolated hotel.'],
  ['Get Out', 2017, ['Jordan Peele'], ['horror', 'thriller'], ['tense', 'cerebral', 'dark'], 'A weekend visit to a girlfriend\'s parents turns sinister.'],
  ['Groundhog Day', 1993, ['Harold Ramis'], ['comedy', 'romance', 'fantasy'], ['funny', 'uplifting', 'romantic'], 'A cynical weatherman relives the same day again and again.'],
  ['The Big Lebowski', 1998, ['Joel Coen', 'Ethan Coen'], ['comedy', 'crime'], ['funny', 'weird', 'chill'], 'A laid-back bowler gets caught up in a kidnapping plot.'],
  ['Superbad', 2007, ['Greg Mottola'], ['comedy'], ['funny', 'nostalgic'], 'Two high-school friends try to make one last party count.'],
  ['The Grand Budapest Hotel', 2014, ['Wes Anderson'], ['comedy', 'drama'], ['funny', 'nostalgic', 'weird'], 'A legendary concierge and his lobby boy are drawn into a theft.'],
  ['Arrival', 2016, ['Denis Villeneuve'], ['sci-fi', 'drama'], ['cerebral', 'emotional', 'atmospheric'], 'A linguist works to communicate with alien visitors.'],
  ['Blade Runner 2049', 2017, ['Denis Villeneuve'], ['sci-fi', 'mystery'], ['atmospheric', 'cerebral', 'dark'], 'A replicant hunter uncovers a secret that could upend society.'],
  ['Sicario', 2015, ['Denis Villeneuve'], ['crime', 'thriller'], ['tense', 'gritty', 'dark'], 'An FBI agent joins a murky task force on the US–Mexico border.'],
  ['No Country for Old Men', 2007, ['Joel Coen', 'Ethan Coen'], ['crime', 'thriller', 'western'], ['tense', 'dark', 'gritty'], 'A hunter takes drug money and is pursued by a relentless killer.'],
  ['There Will Be Blood', 2007, ['Paul Thomas Anderson'], ['drama', 'western'], ['dark', 'epic', 'gritty'], 'An oil prospector\'s ambition consumes him.'],
  ['Moonlight', 2016, ['Barry Jenkins'], ['drama'], ['emotional', 'atmospheric', 'romantic'], 'Three chapters in the life of a young man growing up in Miami.'],
  ['Parasite', 2019, ['Bong Joon-ho'], ['thriller', 'drama', 'comedy'], ['tense', 'dark', 'funny'], 'A poor family schemes its way into a wealthy household.'],
  ['Spirited Away', 2001, ['Hayao Miyazaki'], ['animation', 'fantasy'], ['weird', 'uplifting', 'atmospheric'], 'A girl is trapped in a world of spirits and must find her way home.'],
  ['Eternal Sunshine of the Spotless Mind', 2004, ['Michel Gondry'], ['romance', 'sci-fi', 'drama'], ['romantic', 'emotional', 'weird'], 'A couple erase each other from their memories.'],
  ['Inception', 2010, ['Christopher Nolan'], ['sci-fi', 'action', 'thriller'], ['cerebral', 'epic', 'tense'], 'A thief who steals secrets through dreams takes one last job.'],
  ['Alien', 1979, ['Ridley Scott'], ['horror', 'sci-fi'], ['dark', 'tense', 'atmospheric'], 'The crew of a cargo ship encounter a deadly lifeform.'],
  ['Paddington 2', 2017, ['Paul King'], ['comedy', 'fantasy'], ['uplifting', 'funny'], 'Paddington is wrongly jailed and must clear his name.'],
  ['Once Upon a Time in the West', 1968, ['Sergio Leone'], ['western'], ['epic', 'atmospheric', 'gritty'], 'A mysterious harmonica player seeks revenge in the old West.'],
  ['Everything Everywhere All at Once', 2022, ['Daniel Kwan', 'Daniel Scheinert'], ['sci-fi', 'comedy', 'action'], ['weird', 'emotional', 'funny'], 'A laundromat owner is pulled into a multiverse crisis.'],
];

export const TV = [
  ['The Sopranos', 1999, ['David Chase'], ['crime', 'drama'], ['dark', 'funny', 'gritty'], 'A New Jersey mob boss sees a therapist.'],
  ['The Wire', 2002, ['David Simon'], ['crime', 'drama'], ['gritty', 'cerebral', 'tense'], 'Baltimore\'s drug trade, seen through police, dealers, unions, politics and schools.'],
  ['Breaking Bad', 2008, ['Vince Gilligan'], ['crime', 'drama', 'thriller'], ['tense', 'dark', 'gritty'], 'A chemistry teacher turns to making meth.'],
  ['True Detective', 2014, ['Nic Pizzolatto'], ['crime', 'mystery', 'drama'], ['dark', 'atmospheric', 'cerebral'], 'Two detectives hunt a ritual killer in Louisiana (season one).'],
  ['Twin Peaks', 1990, ['David Lynch', 'Mark Frost'], ['mystery', 'drama', 'horror'], ['weird', 'atmospheric', 'dark'], 'An FBI agent investigates a homecoming queen\'s murder.'],
  ['Mindhunter', 2017, ['Joe Penhall', 'David Fincher'], ['crime', 'drama'], ['dark', 'cerebral', 'tense'], 'FBI agents pioneer criminal profiling in the 1970s.'],
  ['Fleabag', 2016, ['Phoebe Waller-Bridge'], ['comedy', 'drama'], ['funny', 'emotional', 'romantic'], 'A sharp, grieving woman navigates life in London.'],
  ['The Office (UK)', 2001, ['Ricky Gervais', 'Stephen Merchant'], ['comedy'], ['funny', 'nostalgic'], 'A mockumentary about a Slough paper merchant\'s office.'],
  ['Parks and Recreation', 2009, ['Greg Daniels', 'Michael Schur'], ['comedy'], ['funny', 'uplifting'], 'An optimistic bureaucrat in a small Indiana town.'],
  ['Arrested Development', 2003, ['Mitchell Hurwitz'], ['comedy'], ['funny', 'weird'], 'A wealthy family loses everything.'],
  ['What We Do in the Shadows', 2019, ['Jemaine Clement'], ['comedy', 'horror'], ['funny', 'weird'], 'Vampire flatmates on Staten Island.'],
  ['The Bear', 2022, ['Christopher Storer'], ['drama', 'comedy'], ['tense', 'emotional', 'high-energy'], 'A fine-dining chef takes over his family\'s sandwich shop.'],
  ['Severance', 2022, ['Dan Erickson'], ['sci-fi', 'thriller', 'mystery'], ['weird', 'cerebral', 'tense'], 'Office workers have their work and home memories surgically split.'],
  ['Succession', 2018, ['Jesse Armstrong'], ['drama', 'comedy'], ['dark', 'funny', 'tense'], 'A media dynasty fights over who takes over.'],
  ['Game of Thrones', 2011, ['David Benioff', 'D. B. Weiss'], ['fantasy', 'drama', 'action'], ['epic', 'dark', 'tense'], 'Noble houses fight for the Iron Throne.'],
  ['The Haunting of Hill House', 2018, ['Mike Flanagan'], ['horror', 'drama'], ['dark', 'emotional', 'atmospheric'], 'Siblings confront the haunted house they grew up in.'],
  ['Stranger Things', 2016, ['The Duffer Brothers'], ['sci-fi', 'horror', 'drama'], ['nostalgic', 'tense', 'weird'], 'Kids in 1980s Indiana face a supernatural threat.'],
  ['Battlestar Galactica', 2004, ['Ronald D. Moore'], ['sci-fi', 'drama', 'action'], ['tense', 'epic', 'gritty'], 'Humanity\'s survivors flee the Cylons.'],
  ['Band of Brothers', 2001, ['Tom Hanks', 'Steven Spielberg'], ['drama', 'action'], ['epic', 'gritty', 'emotional'], 'Easy Company from D-Day to the end of WWII.'],
  ['Atlanta', 2016, ['Donald Glover'], ['comedy', 'drama'], ['weird', 'funny', 'cerebral'], 'Two cousins work their way through the Atlanta rap scene.'],
  ['Planet Earth II', 2016, ['David Attenborough'], ['documentary'], ['epic', 'atmospheric', 'uplifting'], 'Wildlife filmed across the planet\'s habitats.'],
  ['Slow Horses', 2022, ['Will Smith'], ['thriller', 'drama', 'comedy'], ['tense', 'funny', 'gritty'], 'Disgraced MI5 agents are exiled to Slough House.'],
];

export const BOOKS = [
  ['Blood Meridian', 1985, ['Cormac McCarthy'], ['literary fiction', 'western'], ['dark', 'epic', 'gritty'], 'A teenager rides with a band of scalp hunters on the 1840s border.'],
  ['The Road', 2006, ['Cormac McCarthy'], ['literary fiction', 'sci-fi'], ['dark', 'emotional', 'atmospheric'], 'A father and son walk through a burned America.'],
  ['The Secret History', 1992, ['Donna Tartt'], ['literary fiction', 'mystery'], ['dark', 'cerebral', 'atmospheric'], 'Classics students at a Vermont college commit a murder.'],
  ['A Little Life', 2015, ['Hanya Yanagihara'], ['literary fiction'], ['emotional', 'dark'], 'Four friends in New York over several decades.'],
  ['Normal People', 2018, ['Sally Rooney'], ['literary fiction', 'romance'], ['romantic', 'emotional'], 'Two Irish teenagers drift together and apart.'],
  ['Dune', 1965, ['Frank Herbert'], ['sci-fi'], ['epic', 'cerebral', 'atmospheric'], 'A noble heir on a desert planet becomes a messiah.'],
  ['Neuromancer', 1984, ['William Gibson'], ['sci-fi'], ['gritty', 'weird', 'high-energy'], 'A washed-up hacker is hired for one last job.'],
  ['The Left Hand of Darkness', 1969, ['Ursula K. Le Guin'], ['sci-fi'], ['cerebral', 'atmospheric'], 'An envoy visits a planet whose people have no fixed gender.'],
  ['Project Hail Mary', 2021, ['Andy Weir'], ['sci-fi'], ['uplifting', 'funny', 'cerebral'], 'A lone astronaut wakes up with no memory and a mission to save Earth.'],
  ['The Name of the Wind', 2007, ['Patrick Rothfuss'], ['fantasy'], ['epic', 'nostalgic'], 'A legendary wizard tells his own story.'],
  ['The Lord of the Rings', 1954, ['J. R. R. Tolkien'], ['fantasy'], ['epic', 'atmospheric'], 'The quest to destroy the One Ring.'],
  ['Piranesi', 2020, ['Susanna Clarke'], ['fantasy', 'mystery'], ['weird', 'atmospheric', 'cerebral'], 'A man lives alone in an endless house of halls and tides.'],
  ['The Shining (novel)', 1977, ['Stephen King'], ['horror'], ['dark', 'tense', 'atmospheric'], 'King\'s novel of the Overlook Hotel.'],
  ['Mexican Gothic', 2020, ['Silvia Moreno-Garcia'], ['horror', 'mystery'], ['dark', 'atmospheric', 'weird'], 'A socialite investigates her cousin\'s new husband\'s decaying mansion.'],
  ['House of Leaves', 2000, ['Mark Z. Danielewski'], ['horror', 'literary fiction'], ['weird', 'dark', 'cerebral'], 'A house that is bigger inside than out.'],
  ['The Haunting of Hill House (novel)', 1959, ['Shirley Jackson'], ['horror'], ['dark', 'atmospheric', 'tense'], 'Four people stay in a notoriously haunted house.'],
  ['Gone Girl', 2012, ['Gillian Flynn'], ['thriller', 'crime'], ['tense', 'dark'], 'A wife goes missing on her fifth anniversary.'],
  ['The Big Sleep', 1939, ['Raymond Chandler'], ['crime', 'mystery'], ['gritty', 'atmospheric'], 'Philip Marlowe takes a blackmail case.'],
  ['Good Omens', 1990, ['Terry Pratchett', 'Neil Gaiman'], ['fantasy', 'humour'], ['funny', 'weird'], 'An angel and a demon try to stop the apocalypse.'],
  ['Lessons in Chemistry', 2022, ['Bonnie Garmus'], ['literary fiction', 'humour'], ['funny', 'uplifting'], 'A chemist in the 1960s ends up hosting a TV cooking show.'],
  ['Sapiens', 2011, ['Yuval Noah Harari'], ['non-fiction', 'history'], ['cerebral'], 'A brief history of humankind.'],
  ['Into Thin Air', 1997, ['Jon Krakauer'], ['non-fiction'], ['tense', 'emotional'], 'An account of the 1996 Everest disaster.'],
  ['Just Kids', 2010, ['Patti Smith'], ['biography'], ['nostalgic', 'emotional', 'romantic'], 'Patti Smith and Robert Mapplethorpe in 1970s New York.'],
  ['Station Eleven', 2014, ['Emily St. John Mandel'], ['literary fiction', 'sci-fi'], ['emotional', 'atmospheric', 'uplifting'], 'A travelling theatre troupe after a pandemic.'],
];

export const MUSIC = [
  ['Homework', 1997, ['Daft Punk'], ['house', 'electronic'], ['high-energy', 'uplifting'], 'Daft Punk\'s debut album.'],
  ['Discovery', 2001, ['Daft Punk'], ['house', 'electronic', 'pop'], ['uplifting', 'high-energy', 'nostalgic']],
  ['Settle', 2013, ['Disclosure'], ['house', 'electronic'], ['high-energy', 'uplifting']],
  ['Untrue', 2007, ['Burial'], ['electronic'], ['dark', 'atmospheric', 'emotional']],
  ['Immunity', 2013, ['Jon Hopkins'], ['techno', 'electronic', 'ambient'], ['atmospheric', 'high-energy', 'emotional']],
  ['Tri Repetae', 1995, ['Autechre'], ['electronic'], ['weird', 'cerebral', 'dark']],
  ['Selected Ambient Works 85–92', 1992, ['Aphex Twin'], ['electronic', 'ambient', 'techno'], ['atmospheric', 'nostalgic', 'weird']],
  ['Music for Airports', 1978, ['Brian Eno'], ['ambient'], ['chill', 'atmospheric']],
  ['In Colour', 2015, ['Jamie xx'], ['house', 'electronic'], ['uplifting', 'nostalgic', 'chill']],
  ['Kid A', 2000, ['Radiohead'], ['rock', 'electronic'], ['atmospheric', 'weird', 'dark']],
  ['OK Computer', 1997, ['Radiohead'], ['rock'], ['atmospheric', 'emotional', 'cerebral']],
  ['Led Zeppelin IV', 1971, ['Led Zeppelin'], ['rock'], ['high-energy', 'epic']],
  ['Is This It', 2001, ['The Strokes'], ['rock', 'indie'], ['high-energy', 'nostalgic']],
  ['Rumours', 1977, ['Fleetwood Mac'], ['rock', 'pop'], ['emotional', 'romantic', 'nostalgic']],
  ['Funeral', 2004, ['Arcade Fire'], ['indie', 'rock'], ['emotional', 'epic', 'uplifting']],
  ['Pink Moon', 1972, ['Nick Drake'], ['folk'], ['chill', 'emotional', 'atmospheric']],
  ['For Emma, Forever Ago', 2007, ['Bon Iver'], ['folk', 'indie'], ['emotional', 'chill', 'atmospheric']],
  ['Fleet Foxes', 2008, ['Fleet Foxes'], ['folk', 'indie'], ['atmospheric', 'uplifting', 'nostalgic']],
  ['Carrie & Lowell', 2015, ['Sufjan Stevens'], ['folk', 'indie'], ['emotional', 'chill']],
  ['Blue', 1971, ['Joni Mitchell'], ['folk'], ['emotional', 'romantic']],
  ['The Freewheelin\' Bob Dylan', 1963, ['Bob Dylan'], ['folk'], ['cerebral', 'nostalgic']],
  ['Kind of Blue', 1959, ['Miles Davis'], ['jazz'], ['chill', 'atmospheric', 'cerebral']],
  ['What\'s Going On', 1971, ['Marvin Gaye'], ['soul'], ['emotional', 'romantic', 'cerebral']],
  ['To Pimp a Butterfly', 2015, ['Kendrick Lamar'], ['hip-hop', 'jazz'], ['cerebral', 'gritty', 'emotional']],
  ['Illmatic', 1994, ['Nas'], ['hip-hop'], ['gritty', 'nostalgic']],
  ['Master of Puppets', 1986, ['Metallica'], ['metal'], ['dark', 'high-energy', 'epic']],
  ['Golden Hour', 2018, ['Kacey Musgraves'], ['country', 'pop'], ['uplifting', 'romantic', 'chill']],
  ['Melodrama', 2017, ['Lorde'], ['pop'], ['emotional', 'high-energy']],
];

// Fictional upcoming titles so the Radar page has something in it before a
// TMDB key is set. They're flagged is_demo and the UI labels them.
export const DEMO_UPCOMING = [
  ['movie', 'Saltmarsh', ['horror', 'mystery'], ['dark', 'atmospheric'], 'in_production', 'Folk-horror about a drowned village that resurfaces in a drought.'],
  ['movie', 'Night Shift Protocol', ['action', 'thriller'], ['high-energy', 'tense'], 'upcoming', 'A hospital security guard holds the line during a citywide blackout.'],
  ['movie', 'Small Hours', ['comedy', 'romance'], ['funny', 'romantic'], 'announced', 'Two insomniacs keep meeting at the same 24-hour launderette.'],
  ['tv', 'The Cartographers (S1)', ['sci-fi', 'drama'], ['cerebral', 'weird'], 'in_production', 'Surveyors find a town that isn\'t on any map, and the maps start changing.'],
  ['tv', 'Brine & Bone', ['crime', 'drama'], ['gritty', 'dark'], 'upcoming', 'A fishing-port detective drama.'],
  ['book', 'The Lantern Archive', ['fantasy', 'mystery'], ['atmospheric', 'weird'], 'upcoming', 'A librarian discovers the books are rewriting their readers.'],
  ['book', 'Dry County', ['literary fiction', 'crime'], ['gritty', 'emotional'], 'announced', 'A drought, a disappearance and a family\'s secrets in rural Texas.'],
  ['music', 'Afterglow Sessions', ['house', 'electronic'], ['uplifting', 'high-energy'], 'upcoming', 'A deep-house LP built from field recordings.'],
  ['music', 'Hollow Pines', ['folk', 'indie'], ['chill', 'emotional'], 'announced', 'A folk album recorded in a forest cabin.'],
  ['music', 'Static Cathedral', ['rock', 'metal'], ['dark', 'epic'], 'in_production', 'Post-metal with choirs.'],
];
